// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: folders.sql

package db

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const countFolderUsers = `-- name: CountFolderUsers :many
SELECT folder_id, count(*) AS n FROM users WHERE folder_id IS NOT NULL GROUP BY folder_id
`

type CountFolderUsersRow struct {
	FolderID sql.NullInt64
	N        int64
}

// How many users each folder holds, hidden ones too.
func (q *Queries) CountFolderUsers(ctx context.Context) ([]CountFolderUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, countFolderUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountFolderUsersRow{}
	for rows.Next() {
		var i CountFolderUsersRow
		if err := rows.Scan(&i.FolderID, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countFolders = `-- name: CountFolders :one
SELECT count(*) FROM user_folders
`

func (q *Queries) CountFolders(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFolders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFolder = `-- name: CreateFolder :one
INSERT INTO user_folders (name, color, emoji, sort, created_at)
VALUES ($1, $2, $3, (SELECT COALESCE(MAX(sort), 0) + 1 FROM user_folders), $4)
RETURNING id, name, color, emoji, sort, created_at
`

type CreateFolderParams struct {
	Name      string
	Color     string
	Emoji     string
	CreatedAt int64
}

// A new folder goes last.
func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) (UserFolder, error) {
	row := q.db.QueryRowContext(ctx, createFolder,
		arg.Name,
		arg.Color,
		arg.Emoji,
		arg.CreatedAt,
	)
	var i UserFolder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.Emoji,
		&i.Sort,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFolder = `-- name: DeleteFolder :execrows
DELETE FROM user_folders WHERE id = $1
`

// Its users stay: their folder is cleared by the foreign key.
func (q *Queries) DeleteFolder(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteFolder, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getFolder = `-- name: GetFolder :one
SELECT id, name, color, emoji, sort, created_at FROM user_folders WHERE id = $1
`

func (q *Queries) GetFolder(ctx context.Context, id int64) (UserFolder, error) {
	row := q.db.QueryRowContext(ctx, getFolder, id)
	var i UserFolder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.Emoji,
		&i.Sort,
		&i.CreatedAt,
	)
	return i, err
}

const listFolders = `-- name: ListFolders :many
SELECT id, name, color, emoji, sort, created_at FROM user_folders ORDER BY sort, id
`

func (q *Queries) ListFolders(ctx context.Context) ([]UserFolder, error) {
	rows, err := q.db.QueryContext(ctx, listFolders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserFolder{}
	for rows.Next() {
		var i UserFolder
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.Emoji,
			&i.Sort,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockFolder = `-- name: LockFolder :one
SELECT id FROM user_folders WHERE id = $1 FOR KEY SHARE
`

// The folder, kept from being deleted until the transaction ends: a user moved into it
// cannot meet a folder that is gone.
func (q *Queries) LockFolder(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, lockFolder, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const setFolderSort = `-- name: SetFolderSort :exec
UPDATE user_folders SET sort = $1 WHERE id = $2
`

type SetFolderSortParams struct {
	Sort int64
	ID   int64
}

func (q *Queries) SetFolderSort(ctx context.Context, arg SetFolderSortParams) error {
	_, err := q.db.ExecContext(ctx, setFolderSort, arg.Sort, arg.ID)
	return err
}

const setUserFolder = `-- name: SetUserFolder :exec
UPDATE users SET folder_id = $1::bigint, updated_at = $2 WHERE id = $3
`

type SetUserFolderParams struct {
	FolderID  sql.NullInt64
	UpdatedAt int64
	ID        int64
}

func (q *Queries) SetUserFolder(ctx context.Context, arg SetUserFolderParams) error {
	_, err := q.db.ExecContext(ctx, setUserFolder, arg.FolderID, arg.UpdatedAt, arg.ID)
	return err
}

const setUserHidden = `-- name: SetUserHidden :exec
UPDATE users SET hidden = $1::bigint, updated_at = $2 WHERE id = $3
`

type SetUserHiddenParams struct {
	Hidden    int64
	UpdatedAt int64
	ID        int64
}

func (q *Queries) SetUserHidden(ctx context.Context, arg SetUserHiddenParams) error {
	_, err := q.db.ExecContext(ctx, setUserHidden, arg.Hidden, arg.UpdatedAt, arg.ID)
	return err
}

const setUsersFolder = `-- name: SetUsersFolder :exec
UPDATE users SET folder_id = $1::bigint, updated_at = $2 WHERE id = ANY($3::bigint[])
`

type SetUsersFolderParams struct {
	FolderID  sql.NullInt64
	UpdatedAt int64
	Ids       []int64
}

// No folder (NULL) takes the users out of theirs.
func (q *Queries) SetUsersFolder(ctx context.Context, arg SetUsersFolderParams) error {
	_, err := q.db.ExecContext(ctx, setUsersFolder, arg.FolderID, arg.UpdatedAt, pq.Array(arg.Ids))
	return err
}

const setUsersHidden = `-- name: SetUsersHidden :exec
UPDATE users SET hidden = $1::bigint, updated_at = $2 WHERE id = ANY($3::bigint[])
`

type SetUsersHiddenParams struct {
	Hidden    int64
	UpdatedAt int64
	Ids       []int64
}

func (q *Queries) SetUsersHidden(ctx context.Context, arg SetUsersHiddenParams) error {
	_, err := q.db.ExecContext(ctx, setUsersHidden, arg.Hidden, arg.UpdatedAt, pq.Array(arg.Ids))
	return err
}

const updateFolder = `-- name: UpdateFolder :one
UPDATE user_folders SET name = $1, color = $2, emoji = $3 WHERE id = $4 RETURNING id, name, color, emoji, sort, created_at
`

type UpdateFolderParams struct {
	Name  string
	Color string
	Emoji string
	ID    int64
}

func (q *Queries) UpdateFolder(ctx context.Context, arg UpdateFolderParams) (UserFolder, error) {
	row := q.db.QueryRowContext(ctx, updateFolder,
		arg.Name,
		arg.Color,
		arg.Emoji,
		arg.ID,
	)
	var i UserFolder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.Emoji,
		&i.Sort,
		&i.CreatedAt,
	)
	return i, err
}
