// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nodetraffic.sql

package db

import (
	"context"
)

const addNodeTraffic = `-- name: AddNodeTraffic :exec
WITH n AS (SELECT id FROM nodes WHERE id = $3::bigint FOR KEY SHARE),
h AS (
  INSERT INTO node_traffic_hourly (node_id, hour, up, down)
  SELECT n.id, $4::bigint, $1::bigint, $2::bigint FROM n
  ON CONFLICT (node_id, hour) DO UPDATE SET up = node_traffic_hourly.up + excluded.up, down = node_traffic_hourly.down + excluded.down
), d AS (
  INSERT INTO node_traffic_daily (node_id, day, up, down)
  SELECT n.id, $5::bigint, $1::bigint, $2::bigint FROM n
  ON CONFLICT (node_id, day) DO UPDATE SET up = node_traffic_daily.up + excluded.up, down = node_traffic_daily.down + excluded.down
)
UPDATE nodes SET total_up = total_up + $1::bigint, total_down = total_down + $2::bigint
WHERE id IN (SELECT id FROM n)
`

type AddNodeTrafficParams struct {
	Up     int64
	Down   int64
	NodeID int64
	Hour   int64
	Day    int64
}

// What a node carried in a batch: its hour, its day and its running total, in one
// statement. The node is kept from being deleted until the transaction ends; one that is
// gone already is skipped, the rest of the batch still counts.
func (q *Queries) AddNodeTraffic(ctx context.Context, arg AddNodeTrafficParams) error {
	_, err := q.db.ExecContext(ctx, addNodeTraffic,
		arg.Up,
		arg.Down,
		arg.NodeID,
		arg.Hour,
		arg.Day,
	)
	return err
}

const nodeTrafficDaily = `-- name: NodeTrafficDaily :many
SELECT day, up, down FROM node_traffic_daily WHERE node_id = $1 AND day >= $2 ORDER BY day
`

type NodeTrafficDailyParams struct {
	NodeID int64
	Day    int64
}

type NodeTrafficDailyRow struct {
	Day  int64
	Up   int64
	Down int64
}

func (q *Queries) NodeTrafficDaily(ctx context.Context, arg NodeTrafficDailyParams) ([]NodeTrafficDailyRow, error) {
	rows, err := q.db.QueryContext(ctx, nodeTrafficDaily, arg.NodeID, arg.Day)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeTrafficDailyRow{}
	for rows.Next() {
		var i NodeTrafficDailyRow
		if err := rows.Scan(&i.Day, &i.Up, &i.Down); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nodeTrafficHourly = `-- name: NodeTrafficHourly :many
SELECT hour, up, down FROM node_traffic_hourly WHERE node_id = $1 AND hour >= $2 ORDER BY hour
`

type NodeTrafficHourlyParams struct {
	NodeID int64
	Hour   int64
}

type NodeTrafficHourlyRow struct {
	Hour int64
	Up   int64
	Down int64
}

func (q *Queries) NodeTrafficHourly(ctx context.Context, arg NodeTrafficHourlyParams) ([]NodeTrafficHourlyRow, error) {
	rows, err := q.db.QueryContext(ctx, nodeTrafficHourly, arg.NodeID, arg.Hour)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeTrafficHourlyRow{}
	for rows.Next() {
		var i NodeTrafficHourlyRow
		if err := rows.Scan(&i.Hour, &i.Up, &i.Down); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneNodeTrafficDaily = `-- name: PruneNodeTrafficDaily :exec
DELETE FROM node_traffic_daily WHERE day < $1
`

func (q *Queries) PruneNodeTrafficDaily(ctx context.Context, day int64) error {
	_, err := q.db.ExecContext(ctx, pruneNodeTrafficDaily, day)
	return err
}

const pruneNodeTrafficHourly = `-- name: PruneNodeTrafficHourly :exec
DELETE FROM node_traffic_hourly WHERE hour < $1
`

func (q *Queries) PruneNodeTrafficHourly(ctx context.Context, hour int64) error {
	_, err := q.db.ExecContext(ctx, pruneNodeTrafficHourly, hour)
	return err
}

const sumNodesTrafficDaily = `-- name: SumNodesTrafficDaily :many
SELECT node_id, CAST(sum(up) AS BIGINT) AS up, CAST(sum(down) AS BIGINT) AS down
FROM node_traffic_daily WHERE day >= $1 GROUP BY node_id
`

type SumNodesTrafficDailyRow struct {
	NodeID int64
	Up     int64
	Down   int64
}

func (q *Queries) SumNodesTrafficDaily(ctx context.Context, day int64) ([]SumNodesTrafficDailyRow, error) {
	rows, err := q.db.QueryContext(ctx, sumNodesTrafficDaily, day)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumNodesTrafficDailyRow{}
	for rows.Next() {
		var i SumNodesTrafficDailyRow
		if err := rows.Scan(&i.NodeID, &i.Up, &i.Down); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumNodesTrafficHourly = `-- name: SumNodesTrafficHourly :many
SELECT node_id, CAST(sum(up) AS BIGINT) AS up, CAST(sum(down) AS BIGINT) AS down
FROM node_traffic_hourly WHERE hour >= $1 GROUP BY node_id
`

type SumNodesTrafficHourlyRow struct {
	NodeID int64
	Up     int64
	Down   int64
}

// What each node carried since an hour, for the nodes that carried anything.
func (q *Queries) SumNodesTrafficHourly(ctx context.Context, hour int64) ([]SumNodesTrafficHourlyRow, error) {
	rows, err := q.db.QueryContext(ctx, sumNodesTrafficHourly, hour)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumNodesTrafficHourlyRow{}
	for rows.Next() {
		var i SumNodesTrafficHourlyRow
		if err := rows.Scan(&i.NodeID, &i.Up, &i.Down); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
