// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subpage.sql

package db

import (
	"context"
)

const countSubDocs = `-- name: CountSubDocs :one
SELECT COUNT(*) FROM sub_docs
`

func (q *Queries) CountSubDocs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSubDocs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSubDoc = `-- name: CreateSubDoc :one
INSERT INTO sub_docs (title, emoji, body, platform, position, published, created_at, updated_at)
VALUES ($1, $2, $3, $4, (SELECT COALESCE(MAX(d.position), 0) + 1 FROM sub_docs d), $5, $6, $6)
RETURNING id, title, emoji, body, platform, position, published, created_at, updated_at
`

type CreateSubDocParams struct {
	Title     string
	Emoji     string
	Body      string
	Platform  string
	Published int64
	At        int64
}

// A new page goes last.
func (q *Queries) CreateSubDoc(ctx context.Context, arg CreateSubDocParams) (SubDoc, error) {
	row := q.db.QueryRowContext(ctx, createSubDoc,
		arg.Title,
		arg.Emoji,
		arg.Body,
		arg.Platform,
		arg.Published,
		arg.At,
	)
	var i SubDoc
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Emoji,
		&i.Body,
		&i.Platform,
		&i.Position,
		&i.Published,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSubAsset = `-- name: DeleteSubAsset :execrows
DELETE FROM sub_assets WHERE name = $1
`

func (q *Queries) DeleteSubAsset(ctx context.Context, name string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSubAsset, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSubDoc = `-- name: DeleteSubDoc :execrows
DELETE FROM sub_docs WHERE id = $1
`

func (q *Queries) DeleteSubDoc(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSubDoc, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPublishedSubDoc = `-- name: GetPublishedSubDoc :one
SELECT id, title, emoji, body, platform, position, published, created_at, updated_at FROM sub_docs WHERE id = $1 AND published = 1
`

func (q *Queries) GetPublishedSubDoc(ctx context.Context, id int64) (SubDoc, error) {
	row := q.db.QueryRowContext(ctx, getPublishedSubDoc, id)
	var i SubDoc
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Emoji,
		&i.Body,
		&i.Platform,
		&i.Position,
		&i.Published,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubAsset = `-- name: GetSubAsset :one
SELECT name, content_type, data, hash, updated_at FROM sub_assets WHERE name = $1
`

func (q *Queries) GetSubAsset(ctx context.Context, name string) (SubAsset, error) {
	row := q.db.QueryRowContext(ctx, getSubAsset, name)
	var i SubAsset
	err := row.Scan(
		&i.Name,
		&i.ContentType,
		&i.Data,
		&i.Hash,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubDoc = `-- name: GetSubDoc :one
SELECT id, title, emoji, body, platform, position, published, created_at, updated_at FROM sub_docs WHERE id = $1
`

func (q *Queries) GetSubDoc(ctx context.Context, id int64) (SubDoc, error) {
	row := q.db.QueryRowContext(ctx, getSubDoc, id)
	var i SubDoc
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Emoji,
		&i.Body,
		&i.Platform,
		&i.Position,
		&i.Published,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPublishedSubDocs = `-- name: ListPublishedSubDocs :many
SELECT id, title, emoji, platform FROM sub_docs WHERE published = 1 ORDER BY position, id
`

type ListPublishedSubDocsRow struct {
	ID       int64
	Title    string
	Emoji    string
	Platform string
}

// What the subscription page lists: the published pages without their text.
func (q *Queries) ListPublishedSubDocs(ctx context.Context) ([]ListPublishedSubDocsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedSubDocs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedSubDocsRow{}
	for rows.Next() {
		var i ListPublishedSubDocsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Emoji,
			&i.Platform,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubAssetMeta = `-- name: ListSubAssetMeta :many
SELECT name, content_type, hash, OCTET_LENGTH(data)::BIGINT AS size, updated_at FROM sub_assets ORDER BY name
`

type ListSubAssetMetaRow struct {
	Name        string
	ContentType string
	Hash        string
	Size        int64
	UpdatedAt   int64
}

// What the page needs to link the images: no bytes.
func (q *Queries) ListSubAssetMeta(ctx context.Context) ([]ListSubAssetMetaRow, error) {
	rows, err := q.db.QueryContext(ctx, listSubAssetMeta)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubAssetMetaRow{}
	for rows.Next() {
		var i ListSubAssetMetaRow
		if err := rows.Scan(
			&i.Name,
			&i.ContentType,
			&i.Hash,
			&i.Size,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubDocs = `-- name: ListSubDocs :many
SELECT id, title, emoji, body, platform, position, published, created_at, updated_at FROM sub_docs ORDER BY position, id
`

func (q *Queries) ListSubDocs(ctx context.Context) ([]SubDoc, error) {
	rows, err := q.db.QueryContext(ctx, listSubDocs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubDoc{}
	for rows.Next() {
		var i SubDoc
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Emoji,
			&i.Body,
			&i.Platform,
			&i.Position,
			&i.Published,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putSubAsset = `-- name: PutSubAsset :exec
INSERT INTO sub_assets (name, content_type, data, hash, updated_at) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (name) DO UPDATE SET content_type = excluded.content_type, data = excluded.data, hash = excluded.hash, updated_at = excluded.updated_at
`

type PutSubAssetParams struct {
	Name        string
	ContentType string
	Data        []byte
	Hash        string
	UpdatedAt   int64
}

func (q *Queries) PutSubAsset(ctx context.Context, arg PutSubAssetParams) error {
	_, err := q.db.ExecContext(ctx, putSubAsset,
		arg.Name,
		arg.ContentType,
		arg.Data,
		arg.Hash,
		arg.UpdatedAt,
	)
	return err
}

const setSubDocPosition = `-- name: SetSubDocPosition :execrows
UPDATE sub_docs SET position = $2 WHERE id = $1
`

type SetSubDocPositionParams struct {
	ID       int64
	Position int64
}

func (q *Queries) SetSubDocPosition(ctx context.Context, arg SetSubDocPositionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setSubDocPosition, arg.ID, arg.Position)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateSubDoc = `-- name: UpdateSubDoc :one
UPDATE sub_docs SET title = $2, emoji = $3, body = $4, platform = $5, published = $6, updated_at = $7
WHERE id = $1
RETURNING id, title, emoji, body, platform, position, published, created_at, updated_at
`

type UpdateSubDocParams struct {
	ID        int64
	Title     string
	Emoji     string
	Body      string
	Platform  string
	Published int64
	UpdatedAt int64
}

func (q *Queries) UpdateSubDoc(ctx context.Context, arg UpdateSubDocParams) (SubDoc, error) {
	row := q.db.QueryRowContext(ctx, updateSubDoc,
		arg.ID,
		arg.Title,
		arg.Emoji,
		arg.Body,
		arg.Platform,
		arg.Published,
		arg.UpdatedAt,
	)
	var i SubDoc
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Emoji,
		&i.Body,
		&i.Platform,
		&i.Position,
		&i.Published,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
