-- +goose Up
-- Kinkan: node sites (ROADMAP item 2). A site is the checked, repacked archive of a static
-- website (internal/site); a node shows at most one. The archive is kept here, so a backup
-- of the database carries the sites with it.
CREATE TABLE kinkan_sites (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT NOT NULL,
  hash       TEXT NOT NULL UNIQUE,
  title      TEXT NOT NULL DEFAULT '',
  size       BIGINT NOT NULL,
  files      INTEGER NOT NULL,
  archive    BYTEA NOT NULL,
  created_at BIGINT NOT NULL
);

-- A node's site. Deleting the node forgets it; a site a node shows cannot be deleted.
CREATE TABLE kinkan_node_sites (
  node_id BIGINT PRIMARY KEY REFERENCES nodes(id) ON DELETE CASCADE,
  site_id BIGINT NOT NULL REFERENCES kinkan_sites(id) ON DELETE RESTRICT
);
CREATE INDEX kinkan_node_sites_site ON kinkan_node_sites(site_id);

-- +goose Down
DROP TABLE kinkan_node_sites;
DROP TABLE kinkan_sites;
