-- +goose Up
-- Telling users apart: where each came from, the admin's folders, and the ones hidden
-- from the list. Nothing here touches what a user may do: access, billing and the nodes
-- never read these columns.
CREATE TABLE user_folders (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT NOT NULL UNIQUE,
  color      TEXT NOT NULL DEFAULT 'gray', -- a name from the palette the API knows
  emoji      TEXT NOT NULL DEFAULT '',
  sort       BIGINT NOT NULL DEFAULT 0,
  created_at BIGINT NOT NULL
);

-- source: admin (made in the panel or by an API key), bot (bought in the Telegram bot),
-- trial (the bot's free trial), import (brought over from another panel).
ALTER TABLE users ADD COLUMN source TEXT NOT NULL DEFAULT 'admin' CHECK (source IN ('admin', 'bot', 'trial', 'import'));
ALTER TABLE users ADD COLUMN hidden BIGINT NOT NULL DEFAULT 0 CHECK (hidden IN (0, 1));
-- One folder at most; a deleted folder lets its users go, they are not deleted with it.
ALTER TABLE users ADD COLUMN folder_id BIGINT REFERENCES user_folders(id) ON DELETE SET NULL;
CREATE INDEX users_folder ON users (folder_id) WHERE folder_id IS NOT NULL;

-- The users there already are, as well as the records tell. A payment that made the user
-- is a purchase in the bot: a 'new' one, or one that recorded "created" (a renewal of a
-- user deleted meanwhile makes a new user). Then an old panel's link, then the trial's
-- own record, which wins over the rest.
UPDATE users SET source = 'bot' WHERE id IN (
  SELECT user_id FROM payments WHERE user_id IS NOT NULL AND (kind = 'new' OR revert LIKE '%"created":true%'));
UPDATE users SET source = 'import' WHERE id IN (SELECT user_id FROM legacy_sub_tokens);
UPDATE users SET source = 'trial' WHERE id IN (SELECT user_id FROM trials WHERE user_id IS NOT NULL);

-- +goose Down
DROP INDEX users_folder;
ALTER TABLE users DROP COLUMN folder_id;
ALTER TABLE users DROP COLUMN hidden;
ALTER TABLE users DROP COLUMN source;
DROP TABLE user_folders;
