-- +goose Up
-- The subscription page's own instructions (the "documentation in the Mini App"): pages
-- in Markdown the admin writes, listed on the subscription page and in the Mini App in
-- their order. A draft (published = 0) stays in the admin.
CREATE TABLE sub_docs (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title      TEXT NOT NULL,
  emoji      TEXT NOT NULL DEFAULT '',
  body       TEXT NOT NULL DEFAULT '',
  platform   TEXT NOT NULL DEFAULT '' CHECK (platform IN ('','ios','android','windows','macos','linux')),
  position   BIGINT NOT NULL DEFAULT 0,
  published  BIGINT NOT NULL DEFAULT 0 CHECK (published IN (0,1)),
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);
CREATE INDEX sub_docs_order ON sub_docs (position, id);

-- The images of the subscription page the admin uploads, one of each name: the logo and
-- the background. hash names the version in the page's links, so browsers may keep them.
CREATE TABLE sub_assets (
  name         TEXT PRIMARY KEY CHECK (name IN ('logo','background')),
  content_type TEXT NOT NULL CHECK (content_type IN ('image/png','image/jpeg','image/webp')),
  data         BYTEA NOT NULL,
  hash         TEXT NOT NULL,
  updated_at   BIGINT NOT NULL
);

-- +goose Down
DROP TABLE sub_assets;
DROP TABLE sub_docs;
